### ISSUE TITLE
Subscription examples

### ISSUE THREAD

**Issue by arnldmthd** [SmartThingsCommunity/smartthings-core-sdk#85]
Hi,

Everythings seems to work very fine, but Subscriptions documentation is quite messy. I cannot figure out how to subscribe my device events.

**Comment by john-u** [comment]
Hello @arnldmthd, sorry you had trouble with subscriptions. Could you share some specific examples of what you were looking at and where it was confusing (screenshots, links, etc.)? We have since created some issue templates that may be of help in making a new issue with more details as well. I also wanted to point out that the SDK follows very close to the [public SmartThings API reference](https://developer-preview.smartthings.com/api/public/#operation/saveSubscription). Those docs may be of more help.
